const categories=[['🍕','Pizza'],['🍔','Burgers'],['🍣','Sushi'],['🥡','Asian'],['🍜','Uzbek'],['🍟','Fast food'],['🍰','Desserts'],['☕','Coffee'],['🥗','Healthy']];
const restaurants=[
 {name:'Ember & Crust',cuisine:'Pizza · Italian',rating:'4.9',time:'20–30 min',price:'$$',tag:'Free delivery',filter:['fast','top'],image:'https://images.unsplash.com/photo-1579751626657-72bc17010498?auto=format&fit=crop&w=900&q=85'},
 {name:'Juniper Kitchen',cuisine:'Healthy · Bowls',rating:'4.8',time:'25–35 min',price:'$$',tag:'20% off',filter:['top','offers'],image:'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=900&q=85'},
 {name:'Momo House',cuisine:'Asian · Dumplings',rating:'4.7',time:'15–25 min',price:'$',tag:'New',filter:['fast'],image:'https://images.unsplash.com/photo-1496116218417-1a781b1c416c?auto=format&fit=crop&w=900&q=85'},
 {name:'Saffron Table',cuisine:'Uzbek · Comfort food',rating:'4.9',time:'30–40 min',price:'$$$',tag:'Top pick',filter:['top'],image:'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=900&q=85'},
 {name:'Bun Theory',cuisine:'Burgers · American',rating:'4.6',time:'20–30 min',price:'$',tag:'Free delivery',filter:['fast'],image:'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=900&q=85'},
 {name:'Nori Nori',cuisine:'Sushi · Japanese',rating:'4.8',time:'35–45 min',price:'$$$',tag:'15% off',filter:['offers','top'],image:'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?auto=format&fit=crop&w=900&q=85'}
];
const dishes=[
 {name:'Spicy pepperoni',restaurant:'Ember & Crust',price:14.5,description:'Charred pepperoni, hot honey, mozzarella',image:'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?auto=format&fit=crop&w=600&q=85'},
 {name:'Green goddess bowl',restaurant:'Juniper Kitchen',price:12.9,description:'Avocado, greens, grains, lemon tahini',image:'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=600&q=85'},
 {name:'Truffle smash',restaurant:'Bun Theory',price:15.2,description:'Double patty, truffle aioli, crispy onion',image:'https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=600&q=85'},
 {name:'Salmon aburi',restaurant:'Nori Nori',price:18.0,description:'Torched salmon, sushi rice, yuzu kosho',image:'https://images.unsplash.com/photo-1553621042-f6e147245754?auto=format&fit=crop&w=600&q=85'}
];
let cart=[];let activeDish=null;let toastTimer;const favorites=new Set();
const $=id=>document.getElementById(id); const money=n=>`$${n.toFixed(2)}`;
function renderCategories(){ $('categoryGrid').innerHTML=categories.map(([icon,name])=>`<button class="category-card" data-category="${name}"><span class="emoji">${icon}</span><span>${name}</span></button>`).join(''); document.querySelectorAll('.category-card').forEach(b=>b.onclick=()=>{document.querySelectorAll('.category-card').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');showToast(`${b.dataset.category} restaurants are on the way`);});}
function renderRestaurants(filter='all'){const list=filter==='all'?restaurants:restaurants.filter(r=>r.filter.includes(filter));$('restaurantGrid').innerHTML=list.map((r,i)=>`<article class="restaurant-card"><div class="restaurant-photo"><img src="${r.image}" alt="${r.name}"><span class="tag">${r.tag}</span><button class="heart ${favorites.has(r.name)?'is-favorite':''}" aria-label="Favorite ${r.name}" data-restaurant="${r.name}">${favorites.has(r.name)?'♥':'♡'}</button></div><div class="restaurant-body"><h3>${r.name}</h3><p>${r.cuisine}</p><div class="meta"><span class="rating"><span>★</span> ${r.rating}</span><span>◷ ${r.time}</span><span>${r.price}</span></div></div></article>`).join('');document.querySelectorAll('.heart').forEach(button=>button.onclick=()=>{const name=button.dataset.restaurant;if(favorites.has(name)){favorites.delete(name);showToast(`${name} removed from favorites`);}else{favorites.add(name);showToast(`${name} added to favorites`);}renderRestaurants(filter);});document.querySelectorAll('[data-toast]').forEach(b=>b.onclick=()=>showToast(b.dataset.toast));}
function renderDishes(){ $('dishGrid').innerHTML=dishes.map((d,i)=>`<article class="dish-card"><div class="dish-image"><img src="${d.image}" alt="${d.name}"><button class="add-dish" aria-label="Add ${d.name}" data-dish="${i}">+</button></div><h3>${d.name}</h3><p>${d.description}</p><span class="dish-price">${money(d.price)}</span></article>`).join('');document.querySelectorAll('.add-dish').forEach(b=>b.onclick=()=>openDish(Number(b.dataset.dish)));}
function openDish(index){activeDish=dishes[index];$('modalImage').src=activeDish.image;$('modalImage').alt=activeDish.name;$('modalRestaurant').textContent=activeDish.restaurant;$('modalName').textContent=activeDish.name;$('modalDescription').textContent=activeDish.description;$('sizeChoices').innerHTML=['Regular','Large +$3','Family +$6'].map((s,i)=>`<label><input type="radio" name="size" value="${i}" ${i===0?'checked':''}>${s}</label>`).join('');$('extraChoices').innerHTML=['Extra cheese +$1.5','Crispy bacon +$2','Hot sauce +$0.5','Jalapeño +$0.5'].map((s,i)=>`<label><span>${s}</span><input type="checkbox" data-extra="${[1.5,2,.5,.5][i]}"></label>`).join('');document.querySelectorAll('input[name=size],#extraChoices input').forEach(x=>x.onchange=updateModalPrice);updateModalPrice();$('modalBackdrop').classList.add('open');}
function updateModalPrice(){let size=Number(document.querySelector('input[name=size]:checked')?.value||0);let extras=[...document.querySelectorAll('#extraChoices input:checked')].reduce((s,x)=>s+Number(x.dataset.extra),0);$('modalPrice').textContent=money(activeDish.price+[0,3,6][size]+extras);}
function addActiveDish(){let size=document.querySelector('input[name=size]:checked');let extras=[...document.querySelectorAll('#extraChoices input:checked')].map(x=>x.parentElement.querySelector('span').textContent).join(', ');let price=parseFloat($('modalPrice').textContent.slice(1));cart.push({...activeDish,price,size:size?.parentElement.textContent.split(' +')[0]||'Regular',extras});renderCart();$('modalBackdrop').classList.remove('open');openCart();showToast('Added to your cart');}
function renderCart(){let count=cart.length;$('cartCount').textContent=count;$('drawerCount').textContent=count?`(${count})`:'';if(!count){$('cartItems').innerHTML='<div class="empty-cart"><span>✦</span><h3>Your cart is waiting</h3><p>Add something delicious to get started.</p></div>';}else{$('cartItems').innerHTML=cart.map((item,i)=>`<div class="cart-row"><img src="${item.image}" alt="${item.name}"><div><h4>${item.name}</h4><small>${item.size}${item.extras?` · ${item.extras}`:''}</small><div class="qty-controls"><button data-remove="${i}">−</button><span>1</span><button data-toast="More ${item.name} coming soon">+</button></div></div><strong>${money(item.price)}</strong></div>`).join('');document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{cart.splice(Number(b.dataset.remove),1);renderCart();});}let subtotal=cart.reduce((s,x)=>s+x.price,0);$('subtotal').textContent=money(subtotal);$('delivery').textContent=count?'$2.99':'$0.00';$('total').textContent=money(subtotal+(count?2.99:0));document.querySelectorAll('[data-toast]').forEach(b=>b.onclick=()=>showToast(b.dataset.toast));}
function openCart(){$('cartDrawer').classList.add('open');$('drawerBackdrop').classList.add('open');}function closeCart(){$('cartDrawer').classList.remove('open');$('drawerBackdrop').classList.remove('open');}function showToast(message){clearTimeout(toastTimer);$('toast').textContent=message;$('toast').classList.add('show');toastTimer=setTimeout(()=>$('toast').classList.remove('show'),2200);}
renderCategories();renderRestaurants();renderDishes();renderCart();
document.querySelectorAll('.filter-button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.filter-button').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderRestaurants(b.dataset.filter);});$('cartButton').onclick=openCart;$('closeCart').onclick=closeCart;$('drawerBackdrop').onclick=closeCart;$('closeModal').onclick=()=>$('modalBackdrop').classList.remove('open');$('modalBackdrop').onclick=e=>{if(e.target===$('modalBackdrop'))$('modalBackdrop').classList.remove('open')};$('addToCartButton').onclick=addActiveDish;$('exploreButton').onclick=()=>$('restaurants').scrollIntoView();$('allCategories').onclick=()=>showToast('All categories are already here');$('checkoutButton').onclick=()=>cart.length?showToast('Checkout is ready to connect'):showToast('Add a dish before checkout');$('locationButton').onclick=()=>showToast('Delivery location selector opened');$('searchInput').oninput=e=>{let q=e.target.value.toLowerCase();document.querySelectorAll('.restaurant-card').forEach(c=>c.style.display=c.textContent.toLowerCase().includes(q)?'':'none');};document.addEventListener('keydown',e=>{if(e.key==='/'&&document.activeElement.tagName!=='INPUT'){e.preventDefault();$('searchInput').focus();}if(e.key==='Escape'){closeCart();$('modalBackdrop').classList.remove('open');}});